FROM ibmfunctions/action-python-v3.7

RUN apt-get -y update && apt-get -y install gcc

WORKDIR /
RUN mkdir /checkpoint
RUN mkdir /checkpoint/run1
COPY /checkpoint/run_jokes /checkpoint/run1

# Make changes to the requirements/app here.
# This Dockerfile order allows Docker to cache the checkpoint layer
# and improve build times if making changes.
RUN pip3 --no-cache-dir install tensorflow==1.14 gpt-2-simple

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
